language: ruby
cache:
  directories:
    - vendor/bundle
    - build

rvm:
  - 2.3.7

before_install:
  - openssl aes-256-cbc -K $encrypted_12cc71c822da_key -iv $encrypted_12cc71c822da_iv -in .s3_sync.enc -out .s3_sync -d
  - openssl aes-256-cbc -K $encrypted_12cc71c822da_key -iv $encrypted_12cc71c822da_iv -in gdrive.json.enc -out gdrive.json -d
  - bundle install

script:
  - bundle exec ruby download_mp3.rb
  - bundle exec middleman build
  - bundle exec middleman s3_sync
