# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source "http://rubygems.org"

gem "middleman", "~> 3.3.0"
gem "middleman-blog"
gem "ruby-mp3info"
gem "redcarpet"
gem "russian"
gem "nokogiri"
gem "json"
gem "builder"
gem "capistrano"
gem "fog"
gem "unf"
gem "rake"
gem "bluecloth"
